spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://localhost:8090/mybatis_plus?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://localhost:8090/mybatis_plus?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123
mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: deleted
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
  configuration:
    # 选用的日志实现框架 - slf4j
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # 指定自定义类型处理器所在包
  type-handlers-package: priv.wmc.handler
